#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Sun Jul 15 14:31:12 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1366, 737))
        self.records = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        
        # Menu Bar
        self.menu = wx.MenuBar()
        self.record = wx.Menu()
        self.menu.Append(self.record, "Record")
        wxglade_tmp_menu = wx.Menu()
        self.menu.Append(wxglade_tmp_menu, "Sequence")
        wxglade_tmp_menu = wx.Menu()
        self.menu.Append(wxglade_tmp_menu, "Playing")
        wxglade_tmp_menu = wx.Menu()
        self.menu.Append(wxglade_tmp_menu, "Recording")
        wxglade_tmp_menu = wx.Menu()
        self.menu.Append(wxglade_tmp_menu, "Options")
        wxglade_tmp_menu = wx.Menu()
        self.menu.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.menu)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        self.records.InsertColumn(0, "Record", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.records.InsertColumn(1, "Repeat", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.records.InsertColumn(2, "Speed", format=wx.LIST_FORMAT_LEFT, width=-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add((0, 0), 0, 0, 0)
        sizer_1.Add(self.records, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
